<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JarakSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('jaraks')->delete();
        DB::table('jaraks')->insert([

            //jarakpantai teluk penyu ke hotel
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '1',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '2',
            //     'jarak' => '38.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '3',
            //     'jarak' => '38',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '4',
            //     'jarak' => '36.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '5',
            //     'jarak' => '55.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '6',
            //     'jarak' => '56',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '7',
            //     'jarak' => '19',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '8',
            //     'jarak' => '36.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '9',
            //     'jarak' => '28.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '10',
            //     'jarak' => '27.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '11',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '12',
            //     'jarak' => '8.3',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '13',
            //     'jarak' => '8.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '14',
            //     'jarak' => '0.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '15',
            //     'jarak' => '1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '16',
            //     'jarak' => '1.3',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '17',
            //     'jarak' => '1.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '18',
            //     'jarak' => '1.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '19',
            //     'jarak' => '5.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],
            // [
            //     'wisata_id' => '1',
            //     'user_id' => '1',
            //     'hotel_id' => '20',
            //     'jarak' => '1.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'), 
            // ],

            //jarak benteng pendem ke hotel
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '2',
            //     'user_id' => '2',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak Pantai Kamulyan ke hotel
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '1',
            //     'jarak' => '2.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '2',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '3',
            //     'jarak' => '36.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '4',
            //     'jarak' => '35.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '5',
            //     'jarak' => '54',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '6',
            //     'jarak' => '54.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '7',
            //     'jarak' => '16.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '8',
            //     'jarak' => '34.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '9',
            //     'jarak' => '25.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '10',
            //     'jarak' => '25.13',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '11',
            //     'jarak' => '25.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '12',
            //     'jarak' => '5.3',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '13',
            //     'jarak' => '5.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '14',
            //     'jarak' => '3.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '15',
            //     'jarak' => '3',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '16',
            //     'jarak' => '3.41',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '17',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '18',
            //     'jarak' => '2.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '19',
            //     'jarak' => '2.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '3',
            //     'user_id' => '3',
            //     'hotel_id' => '20',
            //     'jarak' => '3.75',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak Pulau Nisakambang ke hotel
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '4',
            //     'user_id' => '4',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak Pantai Widarapayung ke hotel
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '1',
                'jarak' => '4.2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '2',
                'jarak' => '38.8',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '3',
                'jarak' => '38.5',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '4',
                'jarak' => '37.5',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '5',
                'jarak' => '56.7',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '6',
                'jarak' => '57.2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '7',
                'jarak' => '19.7',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '8',
                'jarak' => '37.1',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '9',
                'jarak' => '29.1',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '10',
                'jarak' => '27.7',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '11',
                'jarak' => '28.6',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '12',
                'jarak' => '9.6',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '13',
                'jarak' => '9.8',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '14',
                'jarak' => '1.9',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '15',
                'jarak' => '2.4',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '16',
                'jarak' => '2.5',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '17',
                'jarak' => '2.7',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '18',
                'jarak' => '3.1',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '19',
                'jarak' => '6.6',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'wisata_id' => '5',
                'user_id' => '5',
                'hotel_id' => '20',
                'jarak' => '2.37',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],

            //jarak pantai ketapang indah ke hotel
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '6',
            //     'user_id' => '6',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            
            //jarak pantai sodong ke hotel
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '7',
            //     'user_id' => '7',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak Gunung Selok ke hotel
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '8',
            //     'user_id' => '8',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak Pantai buton ke hotel
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '9',
            //     'user_id' => '9',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak gunung srandil ke hotel
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '10',
            //     'user_id' => '10',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak Susur sungai batik mangrove ke hotel
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '11',
            //     'user_id' => '11',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak Hutan Payau ke hotel
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '12',
            //     'user_id' => '12',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],

            //jarak Air Panas Cipari ke hotel
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '1',
            //     'jarak' => '4.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '2',
            //     'jarak' => '38.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '3',
            //     'jarak' => '38.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '4',
            //     'jarak' => '37.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '5',
            //     'jarak' => '56.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '6',
            //     'jarak' => '57.2',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '7',
            //     'jarak' => '19.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '8',
            //     'jarak' => '37.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '9',
            //     'jarak' => '29.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '10',
            //     'jarak' => '27.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '11',
            //     'jarak' => '28.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '12',
            //     'jarak' => '9.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '13',
            //     'jarak' => '9.8',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '14',
            //     'jarak' => '1.9',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '15',
            //     'jarak' => '2.4',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '16',
            //     'jarak' => '2.5',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '17',
            //     'jarak' => '2.7',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '18',
            //     'jarak' => '3.1',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '19',
            //     'jarak' => '6.6',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
            // [
            //     'wisata_id' => '13',
            //     'user_id' => '13',
            //     'hotel_id' => '20',
            //     'jarak' => '2.37',
            //     'created_at'=>date('Y-m-d H:i:s'),
            //     'updated_at'=>date('Y-m-d H:i:s'),
            // ],
        ]);
    }
}
